global:
    ## Path of directory with which to store all session logs (auth logs go via syslog to /var/log/auth.log or /var/log/secure).
    log_path:       "data/logs"
    ## Array of private keys to identify the server, one per algorithm.
    host_keys:
        - "data/keys/server_key_rsa"
    ## Listen path for setting up the TCP listener.
    ## We don't support droping priviledges, so should be greater than 1024,
    ## so the service can be run as a non-root user.
    ## You can use iptables NATing to redirect users from port 22.
    listen_path:    "0.0.0.0:2222"
    ## Known hosts
    known_hosts_file: "data/known_hosts"
    # Kerberos keytab
    keytab_file: "data/keytab"
keys:
    S-1-5-21-3853463099-2350398476-1773878587-3106:
      - "data/ssh_key"
    S-1-5-21-3853463099-2350398476-1773878587-3107:
      - "data/ssh_key_intern"
    S-1-5-21-3853463099-2350398476-1773878587-3108:
      - "data/ssh_key_ansible"
